-- Admin credential insertions generated by OfflinePasswordHasher

INSERT INTO users (username, email, password, role)
VALUES ('admin', 'pro1570@yahoo.com', '$2a$10$qzyHmOXYCe9Qxwdz2Y0Rwevxy0QoAFs1VZVGc8ro9zRMCxXedmnZi', 'ROLE_ADMIN');
